ARG BASE_MULTIARCH_VERSION
FROM quay.io/qiotproject/ubi-multiarch:$BASE_MULTIARCH_VERSION
ARG DOCKER_ARCH
ARG JAVA_VERSION
LABEL "architecture"="$DOCKER_ARCH"

RUN dnf -y install java-$JAVA_VERSION-openjdk java-$JAVA_VERSION-openjdk-devel maven && dnf clean all
ENV JAVA_HOME=/usr/lib/jvm/jre-$JAVA_VERSION-openjdk
CMD ["/bin/bash"]